# System-wide .bashrc file for interactive bash(1) shells.
# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.
#echo /etc/bashrc
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi


# set a fancy prompt (non-color, overwrite the one in /etc/profile)
#PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

# ANSI color codes
RS=$(tput sgr0)
HC=$(tput bold)    # hicolor
ULS=$(tput smul)    # underline start
ULE=$(tput rmul)    # underline end
INVS=$(tput smso)   # inverse background and foreground start
INVE=$(tput rmso)   # inverse background and foreground end

FBLK=$(tput setaf 0) # foreground black
FRED=$(tput setaf 1) # foreground red
FGRN=$(tput setaf 2) # foreground green
FYEL=$(tput setaf 3) # foreground yellow
FBLE=$(tput setaf 4) # foreground blue
FMAG=$(tput setaf 5) # foreground magenta
FCYN=$(tput setaf 6) # foreground cyan
FWHT=$(tput setaf 7) # foreground white
BBLK=$(tput setab 0) # background black
BRED=$(tput setab 1) # background red
BGRN=$(tput setab 2) # background green
BYEL=$(tput setab 3) # background yellow
BBLE=$(tput setab 4) # background blue
BMAG=$(tput setab 5) # background magenta
BCYN=$(tput setab 6) # background cyan
BWHT=$(tput setab 7) # background white

# Handle root vs normal users for prompt
if [ "`id -u`" -eq 0 ]; then
  PS1COLOUR=$FRED
else
  PS1COLOUR=$FBLE
fi

DIR=/etc/bashrc.d
if [ -d $DIR ]; then
  for i in $DIR/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
unset DIR
source /etc/bashrc.d.direct/git-prompt-settings.sh
source /etc/bashrc.d.direct/git-prompt.sh
if [ "$color_prompt" = yes ]; then
#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    #PS1="$HC$FBLE${debian_chroot:+($debian_chroot)}\u$FYEL: $FBLE\w $FYEL\\$ $RS"
    #PS1="$HC$PS1COLOUR${debian_chroot:+($debian_chroot)}\u@\h$FYEL: $PS1COLOUR\w \\$ $RS"
    #PS1="$FRED [\u@\h \W"$(__git_ps1 " (%s)")"]\$$RS "
    #PS1='$HC$PS1COLOUR${debian_chroot:+($debian_chroot)}\u@\h$FYEL: $PS1COLOUR\w $BWHT$(__git_ps1 "(%s)")$RS$FYEL \t\\$ $RS'
    #PS1='\[$FRED\]${debian_chroot:+($debian_chroot)}\u@\h: \w $(__git_ps1 "(%s)") \t\\$ '
    PS1='\[$HC$PS1COLOUR\]${debian_chroot:+($debian_chroot)}\u@\h\[$FYEL\]: \[$PS1COLOUR\]\W \[$BWHT\]$(__git_ps1 "(%s)")\[$RS$FYEL\]\\$ \[$RS\]'

    #PS1='${debian_chroot:+($debian_chroot)}\u@\h: \w $(__git_ps1 "(%s)") \t\\$ '
    #PS1='\u@\h: \w $(__git_ps1 "(%s)") \t\\$ '
    PS2="$HC$FYEL> $RS"
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
    PS2="> "
fi
unset color_prompt force_color_prompt


# Commented out, don't overwrite xterm -T "title" -n "icontitle" by default.
# If this is an xterm set the title to user@host:dir
#case "$TERM" in
#xterm*|rxvt*)
#    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
#    ;;
#*)
#    ;;
#esac

# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# sudo hint
if [ ! -e "$HOME/.sudo_as_admin_successful" ] && [ ! -e "$HOME/.hushlogin" ] ; then
    case " $(groups) " in *\ admin\ *)
    if [ -x /usr/bin/sudo ]; then
	cat <<-EOF
	To run a command as administrator (user "root"), use "sudo <command>".
	See "man sudo_root" for details.
	
	EOF
    fi
    esac
fi

# if the command-not-found package is installed, use it
if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
	function command_not_found_handle {
	        # check because c-n-f could've been removed in the meantime
                if [ -x /usr/lib/command-not-found ]; then
		   /usr/lib/command-not-found -- "$1"
                   return $?
                elif [ -x /usr/share/command-not-found/command-not-found ]; then
		   /usr/share/command-not-found/command-not-found -- "$1"
                   return $?
		else
		   printf "%s: command not found\n" "$1" >&2
		   return 127
		fi
	}
fi


